event_name = {
    "Marathon Men": "Athletics Mens Marathon",
    "20Km Race Walk Men": "Athletics Mens 20 kilometres Walk",
    "1500M Men": "Athletics Mens 1,500 metres",
    "400M Men": "Athletics Mens 400 metres",
    "10000M Men": "Athletics Mens 10,000 metres",
    "800M Women": "Athletics Womens 800 metres",
    "400M Hurdles Men": "Athletics Mens 400 metres Hurdles",
    "400M Hurdles Women": "Athletics Womens 400 metres Hurdles",
    "100M Men": "Athletics Mens 100 metres",
    "Decathlon Men": "Athletics Mens Decathlon",
    "200M Men": "Athletics Mens 200 metres",
    "3000M Steeplechase Men": "Athletics Mens 3,000 metres Steeplechase",
    "100M Hurdles Women": "Athletics Womens 100 metres Hurdles",
    "1500M Women ": "Athletics Womens 1,500 metres",
    "5000M Men": "Athletics Mens 5,000 metres",
    "100M Women": "Athletics Womens 100 metres",
    "50Km Race Walk Men": "Athletics Mens 50 kilometres Walk",
    "800M Men": "Athletics Mens 800 metres",
    "110M Hurdles Men": "Athletics Mens 110 metres Hurdles",
    "400M Women": "Athletics Womens 400 metres",
    "200M Women": "Athletics Womens 200 metres",
    "High Jump Men": "Athletics Mens High Jump",
    "High Jump Women": "Athletics Womens High Jump",
    "Discus Throw Men": "Athletics Mens Discus Throw",
    "Discus Throw Women": "Athletics Womens Discus Throw",
    "Shot Put Men": "Athletics Mens Shot Put",
    "Shot Put Women": "Athletics Womens Shot Put",
    "Long Jump Men": "Athletics Mens Long Jump",
    "Long Jump Women": "Athletics Womens Long Jump",
    "Marathon Women": "Athletics Womens Marathon",
    "Hammer Throw Men": "Athletics Mens Hammer Throw",
    "Heptathlon Women": "Athletics Womens Heptathlon",
    "Triple Jump Men": "Athletics Mens Triple Jump",
    "10000M Women": "Athletics Womens 10,000 metres",
    "5000M Women": "Athletics Womens 5,000 metres",
    "Triple Jump Women": "Athletics Womens Triple Jump",
    "20Km Race Walk Women": "Athletics Womens 20 kilometres Walk",
    "Hammer Throw Women": "Athletics Womens Hammer Throw",
    "3000M Steeplechase Women": "Athletics Womens 3,000 metres Steeplechase",
    "Javelin Throw Men": "Athletics Mens Javelin Throw",
    "Javelin Throw Women": "Athletics Womens Javelin Throw",
    "Pole Vault Women": "Athletics Womens Pole Vault",
    "Pole Vault Men": "Athletics Mens Pole Vault",
    "1500M Women": "Athletics Womens 1,500 metres"
}
